server:
  servlet:
    context-path: /test
logging:
  file:
    path: logs
  config: classpath:log4j2.xml
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath*:conf/*Mapper.xml
  type-aliases-package: com.maxfan.springbootuxdb.entity
spring:
  datasource:
    dbcp2:
      initial-size: 10
      max-conn-lifetime-millis: 36000000
      max-idle: 10
      max-total: 50
      max-wait-millis: 10000
      min-idle: 5
      validation-query: SELECT 1
    driverClassName: org.postgresql.Driver
    type: org.apache.commons.dbcp2.BasicDataSource
    url: jdbc:postgresql://172.16.3.252:30535/postgresdb
    username: postgresadmin
    password: admin123
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      indent-output: true
    time-zone: GMT
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
